/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication10;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Dimension;

/**
 *
 * @author nada haninou
 */
public class JFrameX extends javax.swing.JFrame {

    /**
     * Creates new form JFrameX
     */
    public JFrameX() {
        initComponents();
                chargemax.setVisible(false);
                nbplaces.setVisible(false);
                ch.setVisible(false);
                nb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeVehicule = new javax.swing.JComboBox<>();
        ma = new javax.swing.JLabel();
        mo = new javax.swing.JLabel();
        re = new javax.swing.JLabel();
        co = new javax.swing.JLabel();
        BttADD = new javax.swing.JButton();
        ch = new javax.swing.JLabel();
        nb = new javax.swing.JLabel();
        marque = new javax.swing.JTextField();
        modele = new javax.swing.JTextField();
        reference = new javax.swing.JTextField();
        couleur = new javax.swing.JTextField();
        chargemax = new javax.swing.JTextField();
        nbplaces = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        typeVehicule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "voiture", "camionete", "minibus" }));
        typeVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeVehiculeActionPerformed(evt);
            }
        });

        ma.setText("Marque");

        mo.setText("Modele");

        re.setText("Reference");

        co.setText("Couleur");

        BttADD.setText("ajouter");
        BttADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttADDActionPerformed(evt);
            }
        });

        ch.setText("chargemax");

        nb.setText("nbplaces");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeVehicule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(re, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(co, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(modele, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chargemax, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nbplaces, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(BttADD)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(typeVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(marque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch)
                    .addComponent(chargemax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(co, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(couleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nb)
                    .addComponent(nbplaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(BttADD)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttADDActionPerformed
       switch(typeVehicule.getSelectedItem().toString()){
           case "voiture":
           {
               try {
                   voiture();
               } catch (SQLException ex) {
                   Logger.getLogger(JFrameX.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
               break;

           case "camionete":
           {
               try {
                   camionete();
               } catch (SQLException ex) {
                   Logger.getLogger(JFrameX.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
               break;

           case "minibus":
           {
               try {
                   minibus();
               } catch (SQLException ex) {
                   Logger.getLogger(JFrameX.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
               break;

       }
    }//GEN-LAST:event_BttADDActionPerformed

    private void typeVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeVehiculeActionPerformed
            if(typeVehicule.getSelectedItem().toString().equals("voiture")){
                chargemax.setVisible(false);
                nbplaces.setVisible(false);
                ch.setVisible(false);
                nb.setVisible(false);
               
            }
            if(typeVehicule.getSelectedItem().toString().equals("camionete")){
                chargemax.setVisible(true);
                nbplaces.setVisible(false);
                nb.setVisible(false);
                ch.setVisible(true);
               
            }
            if(typeVehicule.getSelectedItem().toString().equals("minibus")){
                chargemax.setVisible(false);
                nbplaces.setVisible(true);
                nb.setVisible(true);
                ch.setVisible(false);
            }
            
            
            
    }//GEN-LAST:event_typeVehiculeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttADD;
    private javax.swing.JLabel ch;
    private javax.swing.JTextField chargemax;
    private javax.swing.JLabel co;
    private javax.swing.JTextField couleur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ma;
    private javax.swing.JTextField marque;
    private javax.swing.JLabel mo;
    private javax.swing.JTextField modele;
    private javax.swing.JLabel nb;
    private javax.swing.JTextField nbplaces;
    private javax.swing.JLabel re;
    private javax.swing.JTextField reference;
    private javax.swing.JComboBox<String> typeVehicule;
    // End of variables declaration//GEN-END:variables

    private void voiture() throws SQLException {
        
            
        String marq=marque.getText();
        String mod=modele.getText();
        String ref=reference.getText();
        String coule=couleur.getText();
        AdministationVoiture adm=new AdministationVoiture();
        boolean b=adm.AjouterVehicule(ref, marq, mod, coule);
        marque.setText("");
        modele.setText("");
        reference.setText("");
        couleur.setText("");
    }

    private void camionete() throws SQLException {
        String marq=marque.getText();
        String mod=modele.getText();
        String ref=reference.getText();
        String coule=couleur.getText();
        String charge=chargemax.getText();
        double ch=Double.parseDouble(charge);
        
        AdministrationCamionette adm=new AdministrationCamionette();
        boolean b=adm.AjouterVehicule(ref, marq, mod, coule,ch);
        marque.setText("");
        modele.setText("");
        reference.setText("");
        couleur.setText("");
        chargemax.setText("");
    }

    private void minibus() throws SQLException {
        String marq=marque.getText();
        String mod=modele.getText();
        String ref=reference.getText();
        String coule=couleur.getText();
        String nbrplaces=nbplaces.getText();
        int ch=Integer.parseInt(nbrplaces);
        
        AdministrationiMiniBus adm=new AdministrationiMiniBus();
        boolean b=adm.AjouterVehicule(ref, marq, mod, coule,ch);
        marque.setText("");
        modele.setText("");
        reference.setText("");
        couleur.setText("");
        nbplaces.setText("");
    }
}
